name: Sable Native Android Port

on:
  workflow_dispatch:
    inputs:
      loader:
        required: true
        default: 'neoforge'
        type: choice
        options:
          - neoforge
          - fabric
      build_ref:
        required: true
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.build_ref }}-${{ github.event.inputs.loader }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build-sable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.build_ref }}
          fetch-depth: 0

      - name: setting version variables
        run: |
          echo "LOADER=${{ github.event.inputs.loader }}" >> $GITHUB_ENV
          echo "VERSION_NAME=${{ github.event.inputs.build_ref }}" >> $GITHUB_ENV

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-01-29
          targets: aarch64-linux-android
          components: rust-src

      - name: setup paths and environment
        run: |
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/25.2.9519653" >> $GITHUB_ENV
          
          CLANG_PATH="${ANDROID_SDK_ROOT}/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$CLANG_PATH" >> $GITHUB_ENV
          echo "CC_aarch64_linux_android=$CLANG_PATH" >> $GITHUB_ENV

      - name: build imgui
        run: |
          sudo apt-get update && sudo apt-get install -y ant
          git clone --depth 1 https://github.com/SpaiR/imgui-java.git
          cd imgui-java
          chmod +x ./gradlew
          
          ./gradlew :imgui-binding:buildNatives -Denvs=android -Dlocal -PandroidNdkPath=$ANDROID_NDK_HOME -PandroidAbi=arm64-v8a
          
          mkdir -p $GITHUB_WORKSPACE/imgui-native-android
          
          IMGUI_SO=$(find . -name "*.so" | grep "arm64-v8a" | head -n 1)
          
          if [ -z "$IMGUI_SO" ]; then
            echo "imgui not found"
            exit 1
          fi

          cp "$IMGUI_SO" $GITHUB_WORKSPACE/imgui-native-android/libimgui-java64.so
          
      - name: setup paths and environment
        run: |
          echo "y" | sudo ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653"
          NDK_PATH="${ANDROID_SDK_ROOT}/ndk/25.2.9519653"
          echo "ANDROID_NDK_HOME=$NDK_PATH" >> $GITHUB_ENV
          
          TOOLCHAIN="$NDK_PATH/toolchains/llvm/prebuilt/linux-x86_64/bin"
          CLANG="$TOOLCHAIN/aarch64-linux-android24-clang"
          
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$CLANG" >> $GITHUB_ENV
          echo "CC_aarch64_linux_android=$CLANG" >> $GITHUB_ENV
          echo "AR_aarch64_linux_android=$TOOLCHAIN/llvm-ar" >> $GITHUB_ENV
          
      - name: build mod
        run: |
          chmod +x ./gradlew
          ./gradlew :${{ env.LOADER }}:assemble -x common:buildRustNatives

      - name: perform jar-jar
        run: |
          mkdir -p final
          
          SABLE_JAR=$(find ${{ env.LOADER }} -name "sable-*.jar" | grep -v "sources" | grep -v "dev" | head -n 1)
          FINAL_NAME="sable-ANDROID-${{ github.event.inputs.build_ref }}.jar"
          cp "$SABLE_JAR" "final/$FINAL_NAME"
          
          mkdir -p final/natives/sable_rapier/
          cp rapier-native-android/sable_rapier_aarch64_linux.so final/natives/sable_rapier/
          
          cd final
          
          zip -u "$FINAL_NAME" natives/sable_rapier/sable_rapier_aarch64_linux.so
          
          VEIL_INTERNAL_PATH=$(unzip -l "$FINAL_NAME" | grep "veil-.*\.jar" | awk '{print $4}' | head -n 1 | tr -d '\r')
          unzip "$FINAL_NAME" "$VEIL_INTERNAL_PATH" -d .
          
          mkdir -p veil_patch
          unzip "$VEIL_INTERNAL_PATH" -d veil_patch/
          TARGET_DIR="veil_patch/io/imgui/java/native-bin/linux-aarch64"
          mkdir -p "$TARGET_DIR"
          cp ../imgui-native-android/libimgui-java64.so "$TARGET_DIR/libimgui-java64.so"
          
          cd veil_patch
          zip -r ../patched_veil.jar .
          cd ..
          
          mv patched_veil.jar "$VEIL_INTERNAL_PATH"
          zip -d "$FINAL_NAME" "META-INF/*.SF" "META-INF/*.RSA" "META-INF/*.DSA" || true
          zip -u "$FINAL_NAME" "$VEIL_INTERNAL_PATH"
          
          echo "ASSET_PATH=final/$FINAL_NAME" >> $GITHUB_ENV

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.ASSET_PATH }}"
          tag_name: "${{ github.event.inputs.build_ref }}"
          name: "Sable Android ${{ github.event.inputs.build_ref }}"
          body: "Sable Android for ${{ github.event.inputs.loader }} loader\nAutomated Build\n\n[View Original Release](https://github.com/ryanhcode/sable/releases/tag/${{ github.event.inputs.build_ref }})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
